# Generated by Django 4.2.4 on 2023-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFile', models.FileField(max_length=256, upload_to='media/videos')),
                ('subtitleFile', models.FileField(blank=True, max_length=256, upload_to='media/subtitles')),
            ],
        ),
    ]
